/*
 * Copyright 2015 Mario_Contreras.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package mx.iteso.msc.sudokuSolver;

import javax.swing.border.Border;

/**
 *
 * @author Mario_Contreras
 */
public class Cell extends javax.swing.JPanel {

    /**
     * Creates new form Cell
     */
    public Cell() {
        initComponents();
    }
    
    public int getValue() {
        return Integer.parseInt(valueField.getText());
    }
    
    public void setValue(int value) {
        valueField.setText(Integer.toString(value));
    }

    public char getLetter() {
        return (char)letterLabel.getText().charAt(0);
    }
    
    public void setLetter(char letter) {
        letterLabel.setText(Character.toString(letter));
    }
    
//    @Override
//    public Border getBorder() {
//        return getBorder();
//    }
//    
//    @Override
//    public void setBorder(Border border) {
//        setBorder(border);
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        valueField = new javax.swing.JTextField();
        letterLabel = new javax.swing.JLabel();

        setBackground(java.awt.Color.white);
        setMaximumSize(new java.awt.Dimension(50, 50));
        setMinimumSize(new java.awt.Dimension(50, 50));
        setPreferredSize(new java.awt.Dimension(50, 50));

        valueField.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        valueField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        valueField.setText("0");
        valueField.setBorder(null);

        letterLabel.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        letterLabel.setText("S");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(letterLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(valueField, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(letterLabel)
                .addGap(1, 1, 1)
                .addComponent(valueField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel letterLabel;
    private javax.swing.JTextField valueField;
    // End of variables declaration//GEN-END:variables
}
